### ISSUE TITLE
Issues cloning & reproducing Sample

### ISSUE THREAD

**Issue by AlxDfy** [macabeus/react-gbajs#13]
After cloning even after npm installing -g react-gbajs I run into both issues:
`Cannot find module 'react-gbajs' or its corresponding type declarations.`
and
`Parameter 'level' implicitly has an 'any' type. TS7006: Parameter 'message' implicitly has an 'any' type.`

Is this package no-longer updated or am I doing something horribly wrong.
Thank you - Getting used to React

**Comment by AlxDfy** [comment]
Update:
After deleting package-lock.json and node_modules before npm install --> npm run start I fixed the cannot find module error in the sample project but still have the following errors:
`TS7006: Parameter 'level' implicitly has an 'any' type.`
and
`TS7006: Parameter 'message' implicitly has an 'any' type.`

The webpage loads but without the emulator screen (image attached)
![image](https://user-images.githubusercontent.com/4674698/127011734-a982b175-2e92-4a21-91e3-b9e7d55bd789.png)

**Comment by macabeus** [comment]
Hey, I updated the readme to explain better how to install this package: https://github.com/macabeus/react-gbajs/commit/5af78d5d0419b1ce74727b3daebcf80ef8593d57
But in short, you shouldn't use `-g`. You should install the dependencies locally.
Both the package's dependencies and for the `/sample` project should be installed locally.

Also, there is no emulator screen per default. You should firstly load a ROM (clicking at the `Choose File` button) and then the emulator will appear.
It should work if you set up the project following the readme. I checked it now.

**Comment by macabeus** [comment]
@AlxDfy Did you solve your problem? Or is there something else?

**Comment by AlxDfy** [comment]
It did not solve my problem, I still ran into the same issues: 
Cannot find module 'react-gbajs' or its corresponding type declarations.
and
Parameter 'level' implicitly has an 'any' type. TS7006: Parameter 'message' implicitly has an 'any' type.

However I assume it is my own env issues and I do not have time to debug currently so will close for now, thank you!
